[build]
  command = "npm run build"
  publish = "_site"

# Optional: redirect root to trailing slash
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# Netlify Identity redirects
[[redirects]]
  from = "/admin/auth"
  to = "/admin/auth.html"
  status = 200

# Handle Netlify Identity callbacks
[[redirects]]
  from = "/.netlify/identity"
  to = "/.netlify/identity"
  status = 200
