backend:
  # Alternativ 1: Netlify Identity + Git Gateway (enkelt)
  # name: git-gateway
  # branch: main

  # Alternativ 2: GitHub (kommentera in och uppdatera repo)
  name: github
  repo: fabian-von-tiedemann/henriksborg-historia
  branch: main

# GitHub OAuth för att komma åt repository
auth:
  - name: github
    client_id: ${GITHUB_CLIENT_ID}
    client_secret: ${GITHUB_CLIENT_SECRET}

site_url: /
logo_url: /assets/hsb/logo.svg

media_folder: "assets/hsb"
public_folder: "/assets/hsb"

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Sidor"
    label_singular: "Sida"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Permalänk", name: "permalink", widget: "string", default: "/{{slug}}/", hint: "Börja och sluta med /" }
      - { label: "Layout", name: "layout", widget: "string", default: "page" }
      - { label: "Innehåll", name: "body", widget: "markdown" }
