backend:
  name: git-gateway
  branch: main

# Netlify Identity-konfiguration
local_backend: false

site_url: /
logo_url: /assets/hsb/logo.svg

media_folder: "assets/hsb"
public_folder: "/assets/hsb"

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Sidor"
    label_singular: "Sida"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Permalänk", name: "permalink", widget: "string", default: "/{{slug}}/", hint: "Börja och sluta med /" }
      - { label: "Layout", name: "layout", widget: "string", default: "page" }
      - { label: "Sammanfattning (för startsidan)", name: "excerpt", widget: "text", hint: "Kort beskrivning som visas på startsidan", required: false }
      - { label: "Huvudbild", name: "featured_image", widget: "image", hint: "Bild som visas på startsidan", required: false }
      - { label: "Innehåll", name: "body", widget: "markdown" }
      - label: "Bilder med bildtexter"
        name: "images"
        widget: "list"
        fields:
          - { label: "Bild", name: "image", widget: "image" }
          - { label: "Bildtext", name: "caption", widget: "string", hint: "Beskrivande text för bilden" }
        hint: "Lägg till bilder med beskrivande texter"
