#!/usr/bin/env bash
set -euo pipefail
mkdir -p assets/hsb
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-1.jpg -> assets/hsb/danvikens-hospital-dh-1.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-1.jpg" -o "assets/hsb/danvikens-hospital-dh-1.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-2.jpg -> assets/hsb/danvikens-hospital-dh-2.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-2.jpg" -o "assets/hsb/danvikens-hospital-dh-2.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-3.jpg -> assets/hsb/danvikens-hospital-dh-3.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-3.jpg" -o "assets/hsb/danvikens-hospital-dh-3.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-4.jpg -> assets/hsb/danvikens-hospital-dh-4.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-4.jpg" -o "assets/hsb/danvikens-hospital-dh-4.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-5-2048x1480.jpeg -> assets/hsb/danvikens-hospital-dh-5-2048x1480.jpeg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-5-2048x1480.jpeg" -o "assets/hsb/danvikens-hospital-dh-5-2048x1480.jpeg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-6.jpg -> assets/hsb/danvikens-hospital-dh-6.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-6.jpg" -o "assets/hsb/danvikens-hospital-dh-6.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-7.jpg -> assets/hsb/danvikens-hospital-dh-7.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-7.jpg" -o "assets/hsb/danvikens-hospital-dh-7.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-8.jpg -> assets/hsb/danvikens-hospital-dh-8.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-8.jpg" -o "assets/hsb/danvikens-hospital-dh-8.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-9.jpg -> assets/hsb/danvikens-hospital-dh-9.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-9.jpg" -o "assets/hsb/danvikens-hospital-dh-9.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-10.jpg -> assets/hsb/danvikens-hospital-dh-10.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-10.jpg" -o "assets/hsb/danvikens-hospital-dh-10.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-11.jpg -> assets/hsb/danvikens-hospital-dh-11.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-11.jpg" -o "assets/hsb/danvikens-hospital-dh-11.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-12-2048x1578.jpg -> assets/hsb/danvikens-hospital-dh-12-2048x1578.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-12-2048x1578.jpg" -o "assets/hsb/danvikens-hospital-dh-12-2048x1578.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-13-2.jpg -> assets/hsb/danvikens-hospital-dh-13-2.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-13-2.jpg" -o "assets/hsb/danvikens-hospital-dh-13-2.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-14.jpg -> assets/hsb/danvikens-hospital-dh-14.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-14.jpg" -o "assets/hsb/danvikens-hospital-dh-14.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-15-2048x1446.jpg -> assets/hsb/danvikens-hospital-dh-15-2048x1446.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-15-2048x1446.jpg" -o "assets/hsb/danvikens-hospital-dh-15-2048x1446.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-16.jpg -> assets/hsb/danvikens-hospital-dh-16.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-16.jpg" -o "assets/hsb/danvikens-hospital-dh-16.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-17.jpg -> assets/hsb/danvikens-hospital-dh-17.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-17.jpg" -o "assets/hsb/danvikens-hospital-dh-17.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-18.jpg -> assets/hsb/danvikens-hospital-dh-18.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-18.jpg" -o "assets/hsb/danvikens-hospital-dh-18.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-20.jpg -> assets/hsb/danvikens-hospital-dh-20.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-20.jpg" -o "assets/hsb/danvikens-hospital-dh-20.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-21.jpg -> assets/hsb/danvikens-hospital-dh-21.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-21.jpg" -o "assets/hsb/danvikens-hospital-dh-21.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-22.jpg -> assets/hsb/danvikens-hospital-dh-22.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-22.jpg" -o "assets/hsb/danvikens-hospital-dh-22.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2023/04/DH-23-2048x1381.jpg -> assets/hsb/danvikens-hospital-dh-23-2048x1381.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2023/04/DH-23-2048x1381.jpg" -o "assets/hsb/danvikens-hospital-dh-23-2048x1381.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-1.jpg -> assets/hsb/finnboda-varv-finn-1.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-1.jpg" -o "assets/hsb/finnboda-varv-finn-1.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-2.jpg -> assets/hsb/finnboda-varv-finn-2.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-2.jpg" -o "assets/hsb/finnboda-varv-finn-2.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-3-2048x1554.jpg -> assets/hsb/finnboda-varv-finn-3-2048x1554.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-3-2048x1554.jpg" -o "assets/hsb/finnboda-varv-finn-3-2048x1554.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-4-2.jpg -> assets/hsb/finnboda-varv-finn-4-2.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-4-2.jpg" -o "assets/hsb/finnboda-varv-finn-4-2.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-5.jpg -> assets/hsb/finnboda-varv-finn-5.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-5.jpg" -o "assets/hsb/finnboda-varv-finn-5.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-6.jpg -> assets/hsb/finnboda-varv-finn-6.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-6.jpg" -o "assets/hsb/finnboda-varv-finn-6.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-7.jpg -> assets/hsb/finnboda-varv-finn-7.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-7.jpg" -o "assets/hsb/finnboda-varv-finn-7.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-8.jpg -> assets/hsb/finnboda-varv-finn-8.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-8.jpg" -o "assets/hsb/finnboda-varv-finn-8.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-9.jpg -> assets/hsb/finnboda-varv-finn-9.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-9.jpg" -o "assets/hsb/finnboda-varv-finn-9.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-10.jpg -> assets/hsb/finnboda-varv-finn-10.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-10.jpg" -o "assets/hsb/finnboda-varv-finn-10.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-11-2.jpg -> assets/hsb/finnboda-varv-finn-11-2.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-11-2.jpg" -o "assets/hsb/finnboda-varv-finn-11-2.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-12.jpg -> assets/hsb/finnboda-varv-finn-12.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-12.jpg" -o "assets/hsb/finnboda-varv-finn-12.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-13.jpg -> assets/hsb/finnboda-varv-finn-13.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-13.jpg" -o "assets/hsb/finnboda-varv-finn-13.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-14.jpg -> assets/hsb/finnboda-varv-finn-14.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-14.jpg" -o "assets/hsb/finnboda-varv-finn-14.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-15.jpg -> assets/hsb/finnboda-varv-finn-15.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-15.jpg" -o "assets/hsb/finnboda-varv-finn-15.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-16.jpg -> assets/hsb/finnboda-varv-finn-16.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-16.jpg" -o "assets/hsb/finnboda-varv-finn-16.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-17.jpg -> assets/hsb/finnboda-varv-finn-17.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-17.jpg" -o "assets/hsb/finnboda-varv-finn-17.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-18.jpg -> assets/hsb/finnboda-varv-finn-18.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-18.jpg" -o "assets/hsb/finnboda-varv-finn-18.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-19.jpg -> assets/hsb/finnboda-varv-finn-19.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-19.jpg" -o "assets/hsb/finnboda-varv-finn-19.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-20.jpg -> assets/hsb/finnboda-varv-finn-20.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-20.jpg" -o "assets/hsb/finnboda-varv-finn-20.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-21.jpg -> assets/hsb/finnboda-varv-finn-21.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-21.jpg" -o "assets/hsb/finnboda-varv-finn-21.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/06/Finn-22.jpg -> assets/hsb/finnboda-varv-finn-22.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/06/Finn-22.jpg" -o "assets/hsb/finnboda-varv-finn-22.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2020/12/HB-boken-kap-1-bild-1.jpg -> assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-1.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2020/12/HB-boken-kap-1-bild-1.jpg" -o "assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-1.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/01/Henriksborg-Vy-över-Danvikskanalens-utlopp.jpg -> assets/hsb/hsb-och-bygget-henriksborg-vy-o-ver-danvikskanalens-utlopp.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/01/Henriksborg-Vy-över-Danvikskanalens-utlopp.jpg" -o "assets/hsb/hsb-och-bygget-henriksborg-vy-o-ver-danvikskanalens-utlopp.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2019/03/1955-Svenska-Oljeslageriaktiebolaget.jpg -> assets/hsb/hsb-och-bygget-1955-svenska-oljeslageriaktiebolaget.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2019/03/1955-Svenska-Oljeslageriaktiebolaget.jpg" -o "assets/hsb/hsb-och-bygget-1955-svenska-oljeslageriaktiebolaget.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2019/03/1955-bild-tagen-från-öster.jpg -> assets/hsb/hsb-och-bygget-1955-bild-tagen-fra-n-o-ster.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2019/03/1955-bild-tagen-från-öster.jpg" -o "assets/hsb/hsb-och-bygget-1955-bild-tagen-fra-n-o-ster.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2019/03/1964-strax-innan-rivning.jpg -> assets/hsb/hsb-och-bygget-1964-strax-innan-rivning.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2019/03/1964-strax-innan-rivning.jpg" -o "assets/hsb/hsb-och-bygget-1964-strax-innan-rivning.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2020/12/HB-boken-kap-1-bild-6-bw.jpg -> assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-6-bw.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2020/12/HB-boken-kap-1-bild-6-bw.jpg" -o "assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-6-bw.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2020/12/Hb-boken-kap-1-bild-7.png -> assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-7.png"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2020/12/Hb-boken-kap-1-bild-7.png" -o "assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-7.png"
echo "Fetching https://henriksborg.se/wp-content/uploads/2020/12/Saltsjöblick-Mockup-2.jpg -> assets/hsb/hsb-och-bygget-saltsjo-blick-mockup-2.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2020/12/Saltsjöblick-Mockup-2.jpg" -o "assets/hsb/hsb-och-bygget-saltsjo-blick-mockup-2.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2020/12/HB-boken-kap-1-bild-9.png -> assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-9.png"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2020/12/HB-boken-kap-1-bild-9.png" -o "assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-9.png"
echo "Fetching https://henriksborg.se/wp-content/uploads/2020/12/HB-boken-kap-1-bild-10.png -> assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-10.png"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2020/12/HB-boken-kap-1-bild-10.png" -o "assets/hsb/hsb-och-bygget-hb-boken-kap-1-bild-10.png"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-1.jpg -> assets/hsb/hammarby-sjo-hsjo--1.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-1.jpg" -o "assets/hsb/hammarby-sjo-hsjo--1.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-2.jpg -> assets/hsb/hammarby-sjo-hsjo--2.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-2.jpg" -o "assets/hsb/hammarby-sjo-hsjo--2.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-3.jpg -> assets/hsb/hammarby-sjo-hsjo--3.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-3.jpg" -o "assets/hsb/hammarby-sjo-hsjo--3.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-4.jpg -> assets/hsb/hammarby-sjo-hsjo--4.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-4.jpg" -o "assets/hsb/hammarby-sjo-hsjo--4.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-5.jpg -> assets/hsb/hammarby-sjo-hsjo--5.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-5.jpg" -o "assets/hsb/hammarby-sjo-hsjo--5.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-6.png -> assets/hsb/hammarby-sjo-hsjo--6.png"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-6.png" -o "assets/hsb/hammarby-sjo-hsjo--6.png"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-7.jpg -> assets/hsb/hammarby-sjo-hsjo--7.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-7.jpg" -o "assets/hsb/hammarby-sjo-hsjo--7.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-8.jpg -> assets/hsb/hammarby-sjo-hsjo--8.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-8.jpg" -o "assets/hsb/hammarby-sjo-hsjo--8.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-9.jpg -> assets/hsb/hammarby-sjo-hsjo--9.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-9.jpg" -o "assets/hsb/hammarby-sjo-hsjo--9.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-10.jpg -> assets/hsb/hammarby-sjo-hsjo--10.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-10.jpg" -o "assets/hsb/hammarby-sjo-hsjo--10.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-11-2048x1311.jpg -> assets/hsb/hammarby-sjo-hsjo--11-2048x1311.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-11-2048x1311.jpg" -o "assets/hsb/hammarby-sjo-hsjo--11-2048x1311.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö-12.png -> assets/hsb/hammarby-sjo-hsjo--12.png"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö-12.png" -o "assets/hsb/hammarby-sjo-hsjo--12.png"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö13-2048x1452.jpg -> assets/hsb/hammarby-sjo-hsjo-13-2048x1452.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö13-2048x1452.jpg" -o "assets/hsb/hammarby-sjo-hsjo-13-2048x1452.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö14.jpg -> assets/hsb/hammarby-sjo-hsjo-14.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö14.jpg" -o "assets/hsb/hammarby-sjo-hsjo-14.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö15.jpg -> assets/hsb/hammarby-sjo-hsjo-15.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö15.jpg" -o "assets/hsb/hammarby-sjo-hsjo-15.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö16.jpg -> assets/hsb/hammarby-sjo-hsjo-16.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö16.jpg" -o "assets/hsb/hammarby-sjo-hsjo-16.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö17-2048x1126.jpg -> assets/hsb/hammarby-sjo-hsjo-17-2048x1126.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö17-2048x1126.jpg" -o "assets/hsb/hammarby-sjo-hsjo-17-2048x1126.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö18.jpg -> assets/hsb/hammarby-sjo-hsjo-18.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö18.jpg" -o "assets/hsb/hammarby-sjo-hsjo-18.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö19.jpg -> assets/hsb/hammarby-sjo-hsjo-19.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö19.jpg" -o "assets/hsb/hammarby-sjo-hsjo-19.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö20.jpg -> assets/hsb/hammarby-sjo-hsjo-20.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö20.jpg" -o "assets/hsb/hammarby-sjo-hsjo-20.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö21.jpg -> assets/hsb/hammarby-sjo-hsjo-21.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö21.jpg" -o "assets/hsb/hammarby-sjo-hsjo-21.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/01/hsjö22.jpg -> assets/hsb/hammarby-sjo-hsjo-22.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/01/hsjö22.jpg" -o "assets/hsb/hammarby-sjo-hsjo-22.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-1.jpg -> assets/hsb/industrialiseringen-ind-1.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-1.jpg" -o "assets/hsb/industrialiseringen-ind-1.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-2.jpg -> assets/hsb/industrialiseringen-ind-2.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-2.jpg" -o "assets/hsb/industrialiseringen-ind-2.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-3-2048x1569.jpg -> assets/hsb/industrialiseringen-ind-3-2048x1569.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-3-2048x1569.jpg" -o "assets/hsb/industrialiseringen-ind-3-2048x1569.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-4.jpg -> assets/hsb/industrialiseringen-ind-4.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-4.jpg" -o "assets/hsb/industrialiseringen-ind-4.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-5.jpg -> assets/hsb/industrialiseringen-ind-5.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-5.jpg" -o "assets/hsb/industrialiseringen-ind-5.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-6-2048x1378.jpg -> assets/hsb/industrialiseringen-ind-6-2048x1378.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-6-2048x1378.jpg" -o "assets/hsb/industrialiseringen-ind-6-2048x1378.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-7-2048x1526.jpg -> assets/hsb/industrialiseringen-ind-7-2048x1526.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-7-2048x1526.jpg" -o "assets/hsb/industrialiseringen-ind-7-2048x1526.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-8.jpg -> assets/hsb/industrialiseringen-ind-8.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-8.jpg" -o "assets/hsb/industrialiseringen-ind-8.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-9.jpg -> assets/hsb/industrialiseringen-ind-9.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-9.jpg" -o "assets/hsb/industrialiseringen-ind-9.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-10.jpg -> assets/hsb/industrialiseringen-ind-10.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-10.jpg" -o "assets/hsb/industrialiseringen-ind-10.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-11-2048x1572.jpg -> assets/hsb/industrialiseringen-ind-11-2048x1572.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-11-2048x1572.jpg" -o "assets/hsb/industrialiseringen-ind-11-2048x1572.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-12.jpg -> assets/hsb/industrialiseringen-ind-12.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-12.jpg" -o "assets/hsb/industrialiseringen-ind-12.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-13-2048x1477.jpg -> assets/hsb/industrialiseringen-ind-13-2048x1477.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-13-2048x1477.jpg" -o "assets/hsb/industrialiseringen-ind-13-2048x1477.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-14-2048x1407.jpg -> assets/hsb/industrialiseringen-ind-14-2048x1407.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-14-2048x1407.jpg" -o "assets/hsb/industrialiseringen-ind-14-2048x1407.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-15.jpg -> assets/hsb/industrialiseringen-ind-15.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-15.jpg" -o "assets/hsb/industrialiseringen-ind-15.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-16.jpg -> assets/hsb/industrialiseringen-ind-16.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-16.jpg" -o "assets/hsb/industrialiseringen-ind-16.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-17.jpg -> assets/hsb/industrialiseringen-ind-17.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-17.jpg" -o "assets/hsb/industrialiseringen-ind-17.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-18.jpg -> assets/hsb/industrialiseringen-ind-18.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-18.jpg" -o "assets/hsb/industrialiseringen-ind-18.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-19.jpg -> assets/hsb/industrialiseringen-ind-19.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-19.jpg" -o "assets/hsb/industrialiseringen-ind-19.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-20.jpg -> assets/hsb/industrialiseringen-ind-20.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-20.jpg" -o "assets/hsb/industrialiseringen-ind-20.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-21.jpg -> assets/hsb/industrialiseringen-ind-21.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-21.jpg" -o "assets/hsb/industrialiseringen-ind-21.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-22.jpg -> assets/hsb/industrialiseringen-ind-22.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-22.jpg" -o "assets/hsb/industrialiseringen-ind-22.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-23.jpg -> assets/hsb/industrialiseringen-ind-23.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-23.jpg" -o "assets/hsb/industrialiseringen-ind-23.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-24-2048x2022.jpeg -> assets/hsb/industrialiseringen-ind-24-2048x2022.jpeg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-24-2048x2022.jpeg" -o "assets/hsb/industrialiseringen-ind-24-2048x2022.jpeg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-25-2048x1409.jpeg -> assets/hsb/industrialiseringen-ind-25-2048x1409.jpeg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-25-2048x1409.jpeg" -o "assets/hsb/industrialiseringen-ind-25-2048x1409.jpeg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/09/Ind-26-2048x1395.jpeg -> assets/hsb/industrialiseringen-ind-26-2048x1395.jpeg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/09/Ind-26-2048x1395.jpeg" -o "assets/hsb/industrialiseringen-ind-26-2048x1395.jpeg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-1.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-1.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-1.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-1.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-2.png -> assets/hsb/kvarnholmen-och-svindersviken-kvh-2.png"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-2.png" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-2.png"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-3.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-3.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-3.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-3.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-4-2048x1497.jpeg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-4-2048x1497.jpeg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-4-2048x1497.jpeg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-4-2048x1497.jpeg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-5.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-5.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-5.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-5.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-6.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-6.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-6.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-6.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-7.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-7.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-7.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-7.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-8-2048x1311.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-8-2048x1311.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-8-2048x1311.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-8-2048x1311.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-9.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-9.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-9.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-9.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-10.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-10.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-10.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-10.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-11.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-11.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-11.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-11.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-12.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-12.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-12.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-12.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-13.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-13.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-13.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-13.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-14-2048x1569.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-14-2048x1569.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-14-2048x1569.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-14-2048x1569.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-15-2048x1389.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-15-2048x1389.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-15-2048x1389.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-15-2048x1389.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-16.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-16.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-16.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-16.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-17.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-17.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-17.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-17.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-18.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-18.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-18.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-18.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-19-2048x1372.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-19-2048x1372.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-19-2048x1372.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-19-2048x1372.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-20.png -> assets/hsb/kvarnholmen-och-svindersviken-kvh-20.png"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-20.png" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-20.png"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-21.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-21.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-21.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-21.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-22.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-22.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-22.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-22.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2024/10/Kvh-23-2048x1425.jpg -> assets/hsb/kvarnholmen-och-svindersviken-kvh-23-2048x1425.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2024/10/Kvh-23-2048x1425.jpg" -o "assets/hsb/kvarnholmen-och-svindersviken-kvh-23-2048x1425.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-1.jpg -> assets/hsb/saltsjoqvarn-sq-1.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-1.jpg" -o "assets/hsb/saltsjoqvarn-sq-1.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-2-2048x1558.jpg -> assets/hsb/saltsjoqvarn-sq-2-2048x1558.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-2-2048x1558.jpg" -o "assets/hsb/saltsjoqvarn-sq-2-2048x1558.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-3.jpg -> assets/hsb/saltsjoqvarn-sq-3.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-3.jpg" -o "assets/hsb/saltsjoqvarn-sq-3.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-4.jpg -> assets/hsb/saltsjoqvarn-sq-4.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-4.jpg" -o "assets/hsb/saltsjoqvarn-sq-4.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-5.jpg -> assets/hsb/saltsjoqvarn-sq-5.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-5.jpg" -o "assets/hsb/saltsjoqvarn-sq-5.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-6.jpg -> assets/hsb/saltsjoqvarn-sq-6.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-6.jpg" -o "assets/hsb/saltsjoqvarn-sq-6.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-7.jpg -> assets/hsb/saltsjoqvarn-sq-7.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-7.jpg" -o "assets/hsb/saltsjoqvarn-sq-7.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-8.jpg -> assets/hsb/saltsjoqvarn-sq-8.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-8.jpg" -o "assets/hsb/saltsjoqvarn-sq-8.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-9.jpg -> assets/hsb/saltsjoqvarn-sq-9.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-9.jpg" -o "assets/hsb/saltsjoqvarn-sq-9.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-10.jpg -> assets/hsb/saltsjoqvarn-sq-10.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-10.jpg" -o "assets/hsb/saltsjoqvarn-sq-10.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-11.jpg -> assets/hsb/saltsjoqvarn-sq-11.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-11.jpg" -o "assets/hsb/saltsjoqvarn-sq-11.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-12.jpg -> assets/hsb/saltsjoqvarn-sq-12.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-12.jpg" -o "assets/hsb/saltsjoqvarn-sq-12.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-13.jpg -> assets/hsb/saltsjoqvarn-sq-13.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-13.jpg" -o "assets/hsb/saltsjoqvarn-sq-13.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-14.jpg -> assets/hsb/saltsjoqvarn-sq-14.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-14.jpg" -o "assets/hsb/saltsjoqvarn-sq-14.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-15.jpg -> assets/hsb/saltsjoqvarn-sq-15.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-15.jpg" -o "assets/hsb/saltsjoqvarn-sq-15.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/SQ-16.jpg -> assets/hsb/saltsjoqvarn-sq-16.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/SQ-16.jpg" -o "assets/hsb/saltsjoqvarn-sq-16.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/SQ-17.jpg -> assets/hsb/saltsjoqvarn-sq-17.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/SQ-17.jpg" -o "assets/hsb/saltsjoqvarn-sq-17.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/SQ-18.jpg -> assets/hsb/saltsjoqvarn-sq-18.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/SQ-18.jpg" -o "assets/hsb/saltsjoqvarn-sq-18.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/SQ-19.jpg -> assets/hsb/saltsjoqvarn-sq-19.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/SQ-19.jpg" -o "assets/hsb/saltsjoqvarn-sq-19.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-20.jpg -> assets/hsb/saltsjoqvarn-sq-20.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-20.jpg" -o "assets/hsb/saltsjoqvarn-sq-20.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-21-1-2048x1391.jpg -> assets/hsb/saltsjoqvarn-sq-21-1-2048x1391.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-21-1-2048x1391.jpg" -o "assets/hsb/saltsjoqvarn-sq-21-1-2048x1391.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-22.jpg -> assets/hsb/saltsjoqvarn-sq-22.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-22.jpg" -o "assets/hsb/saltsjoqvarn-sq-22.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-23-2048x1425.jpg -> assets/hsb/saltsjoqvarn-sq-23-2048x1425.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-23-2048x1425.jpg" -o "assets/hsb/saltsjoqvarn-sq-23-2048x1425.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-24-2048x1385.jpg -> assets/hsb/saltsjoqvarn-sq-24-2048x1385.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-24-2048x1385.jpg" -o "assets/hsb/saltsjoqvarn-sq-24-2048x1385.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-25-scaled.jpg -> assets/hsb/saltsjoqvarn-sq-25-scaled.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-25-scaled.jpg" -o "assets/hsb/saltsjoqvarn-sq-25-scaled.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-26.jpg -> assets/hsb/saltsjoqvarn-sq-26.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-26.jpg" -o "assets/hsb/saltsjoqvarn-sq-26.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-27.jpg -> assets/hsb/saltsjoqvarn-sq-27.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-27.jpg" -o "assets/hsb/saltsjoqvarn-sq-27.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-28.jpg -> assets/hsb/saltsjoqvarn-sq-28.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-28.jpg" -o "assets/hsb/saltsjoqvarn-sq-28.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2021/08/sq-29.jpg -> assets/hsb/saltsjoqvarn-sq-29.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2021/08/sq-29.jpg" -o "assets/hsb/saltsjoqvarn-sq-29.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-1.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-1.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-1.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-1.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-2.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-2.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-2.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-2.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-3.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-3.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-3.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-3.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-4.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-4.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-4.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-4.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-5-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-5-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-5-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-5-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-6.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-6.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-6.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-6.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-7-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-7-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-7-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-7-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-8.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-8.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-8.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-8.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-9-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-9-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-9-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-9-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-10.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-10.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-10.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-10.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-11.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-11.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-11.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-11.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-12-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-12-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-12-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-12-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-13-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-13-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-13-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-13-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-14.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-14.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-14.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-14.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-15-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-15-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-15-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-15-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-16-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-16-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-16-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-16-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-17.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-17.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-17.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-17.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-18.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-18.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-18.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-18.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-19.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-19.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-19.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-19.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-20.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-20.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-20.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-20.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-21.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-21.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-21.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-21.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-22-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-22-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-22-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-22-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-23.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-23.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-23.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-23.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-24-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-24-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-24-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-24-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-25-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-25-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-25-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-25-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-26-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-26-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-26-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-26-800.jpg"
echo "Fetching https://henriksborg.se/wp-content/uploads/2022/03/Historia-27-800.jpg -> assets/hsb/traktens-och-kommunens-historia-historia-27-800.jpg"
curl -L --fail --silent --show-error "https://henriksborg.se/wp-content/uploads/2022/03/Historia-27-800.jpg" -o "assets/hsb/traktens-och-kommunens-historia-historia-27-800.jpg"
echo "Done. Assets saved to assets/hsb/"
